create wb-metapackage source with wb-suite package
wirenboard/wb-metapackages pull request #1
Opened 2021-03-16 12:52 UTC by webconn

2021-03-16 18:11 UTC, evgeny-boger requested changes
Мне кажется уже с самого начала надо разделить пакеты, которые вот прямо совсем-совсем нужны и те, которые обычно ставятся.

Совсем-совсем нужны получается: wb-release-info, wb-configs, wb-dt-overlays, linux-image-wb6, wb-hwconf-manager

2021-03-29 12:42 UTC, webconn commented
Да, согласен. Сейчас тогда получится два метапакета - `wb-essential` с самым-самым необходимым и `wb-suite` как был раньше. Эти пакеты сейчас вроде бы несложно ввернуть в нынешнюю процедуру сборки rootfs без масштабного изучения и переделывания, и для нас будет бонусом, что они будут появляться у пользователей.

Всё дерево метапакетов с тасками для разных таргетов предлагаю сделать позже и вкупе с рефакторингом `create_rootfs.sh`, потому что там сейчас довольно большой и, возможно, хитрый процесс сборки, не хочется сейчас на это тратить время.

2021-04-04 23:33 UTC, evgeny-boger commented on debian/control
> +#        wb-hwconf-manager, wb-dt-overlays
а почему закомментировано?

2021-04-04 23:33 UTC, evgeny-boger commented on debian/control
> +         wb-daemon-watchdogs, wb-mqtt-confed,
wb-daemon-watchdogs уже можно выкинуть думаю

2021-04-04 23:33 UTC, evgeny-boger commented on debian/control
> +Package: wb-suite
какой у нас план по переводу create_rootfs на метапакеты? Появится wb-suite-wb6,wb-suite-wb7,wb-suite-wb5, которые просто будут Provides: wb-suite ?

2021-04-05 06:35 UTC, webconn commented on debian/control
> +#        wb-hwconf-manager, wb-dt-overlays
Потому что надебажил и забыл, ща исправлю

2021-04-05 06:39 UTC, webconn commented on debian/control
> +Package: wb-suite
У меня была идея, что wb-suite будет стоять вообще везде (кроме каких-нибудь Zero) на любых версиях железа, а метапакеты для отдельных версий контроллеров будут называться `task-wbX` и будут устанавливать `wb-essential`, `wb-suite` и сверху ещё что-то специфичное для контроллеров, причём через `Recommends`, как в Debian tasksel, чтобы можно было какие-то пакеты удалять или заменять на другие без адища в зависимостях.

2021-04-22 04:50 UTC, PeteK12 commented on debian/control
> +         wb-mqtt-w1 | wb-homa-w1, wb-mqtt-gpio | wb-homa-gpio, wb-mqtt-adc | wb-homa-adc,
Зачем нам wb-homa-XXX, они ж только для перехода на wb-mqtt-XXX?

2021-04-22 09:47 UTC, webconn commented on debian/control
> +         wb-mqtt-w1 | wb-homa-w1, wb-mqtt-gpio | wb-homa-gpio, wb-mqtt-adc | wb-homa-adc,
Я с удовольствием бы их выкинул, но для armel не собраны wb-mqtt-XXX, и из-за этого не собирались образы для wb5. На wb6 wb-homa-XXX вообще в репозиторий не пойдут, потому ни на что не повлияет. Если починим для wb5, можно будет отсюда убрать эти альтернативы.

2021-04-22 10:05 UTC, PeteK12 commented on debian/control
> +         wb-mqtt-w1 | wb-homa-w1, wb-mqtt-gpio | wb-homa-gpio, wb-mqtt-adc | wb-homa-adc,
Ясно. Не починим, libwbmqtt1 никто не хотел на wb5 портировать.

2021-04-22 10:06 UTC, webconn commented on debian/control
> +         wb-mqtt-w1 | wb-homa-w1, wb-mqtt-gpio | wb-homa-gpio, wb-mqtt-adc | wb-homa-adc,
Починить это можно не портированием libwbmqtt1, а правкой debian/control в старых версиях, чтобы переименовать пакет. Но тоже непонятно, ради чего.

2021-04-22 10:19 UTC, PeteK12 approved these changes

2021-04-22 19:47 UTC, merged